### ISSUE TITLE
setSolution && isSolved FAIL

### ISSUE THREAD

**Issue by pitrrs** [xeeeveee/sudoku#1]
HI,
The data in the image is detected by this class as invalid.
CellSize = 2;

![image](https://user-images.githubusercontent.com/4920476/27610711-c9401922-5b8f-11e7-9017-c693b6b02be6.png)

Any solution? 

Thanks!

**Comment by xeeeveee** [comment]
Hi Pitrrs,

What does the image represent? (Whats been dumped?)

It looks like a solution to a 2x2 grid, if so, what about it is invalid? It appears to be a valid solution?

Thanks,
Jack

**Comment by pitrrs** [comment]
Thank you for the quick reply. 
Yes, it's a dump of data (2x2 grid) that is solved by the user and they are right.
This class evaluates that the solution is wrong, but it is correct.

I have found other cases where the right solution is marked as bad.

**Comment by xeeeveee** [comment]
Ah, interesting - I'll take a look into it for you

**Comment by pitrrs** [comment]
Generated data is (json_encoded):
`[[0,0,1,0],[0,4,0,0],[0,0,0,2],[0,2,0,0]]`

**Comment by xeeeveee** [comment]
Hi Pitrrs,

I've identified and fixed an issue that was causing isSolved() to fail, this was happening when generating a grid of a set size, and then reducing it to a smaller size, oppose to specifying it in the constructor initially.

Presumably you were doing something similar to:
```
$puzzle = new Xeeeveee\Sudoku\Puzzle();
$puzzle->setCellSize(2);
```

However the solution you presented isn't actually valid, if you refer to the readme each nested array is a row, when displayed in that manner you can see the solution provided violates the box constraints:
```
[ 2, 3, 1, 4, ],
[ 3, 4, 2, 1, ],
[ 4, 1, 3, 2, ],
[ 1, 2, 4, 3, ],
```
Two 3's in top left
Two 1's in top right
Two 1's in bottom left
Two 3's in bottom right

Hope this helps :)
